### ISSUE TITLE
Found this issue

### ISSUE THREAD

**Issue by rielinux** [IHosseini083/SuperLink#1]
File "/root/SuperLink/Modules/mapMaker.py", line 3, in <module>
    import folium ModuleNotFoundError: No module named 'folium'

**Comment by IHosseini083** [comment]
Hey there, sorry about that I just forgot to add that module's installation for linux_installer, it's updated now and you can either run this in your terminal `pip3 install folium` or just run the updated `linux_installer` file.
Have a nice day ✌
