### ISSUE TITLE
ERROR getUserData

### ISSUE THREAD

**Issue by An0nH4wk** [IHosseini083/SuperLink#4]
[!] You can close the server by pressing [Ctrl+C] ... 

 <! ----- 1 ----- !> 

 [>] IP   :X.X.X.X
 [>] Time : 2021-08-07 | 01:37:30
 [>] Saving target GeoIP data...         

 **[#getUserData] ERROR : 'data'**

 [!] Press [ENTER] to continue...

**Comment by hieuTranEnouvo** [comment]
I got the error same

**Comment by datlmhg** [comment]
I got the same error too
