### ISSUE TITLE
[#getUserData] ERROR : 'data'

### ISSUE THREAD

**Issue by insogna** [IHosseini083/SuperLink#6]
[!] You can close the server by pressing [Ctrl+C] ...

<! ----- 1 ----- !>

[>] IP :X.X.X.X
[>] Time : 2021-08-07 | 01:37:30
[>] Saving target GeoIP data...

[#getUserData] ERROR : 'data'

[!] Press [ENTER] to continue...

**Comment by datlmhg** [comment]
I got the same error too
