### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by nandharjpm** [IHosseini083/SuperLink#8]
File "/root/SuperLink/SuperLink.py", line 23, in <module>
    from Modules.mapMaker import MapMaker
  File "/root/SuperLink/Modules/mapMaker.py", line 3, in <module>
    import folium
ModuleNotFoundError: No module named 'folium'

**Comment by Manoj0Marmat** [comment]
@nandharjpm there is no issue i found like that

**Comment by Manoj0Marmat** [comment]
@nandharjpm run linux_installer.sh file before run SuperLink.py file
